export const PRODUCT_DASHBOARD_DEFAULT_LIMIT = 5;
export const PRODUCT_DASHBOARD_MAX_LIMIT = 10;
export const PRODUCT_DASHBOARD_MAX_RANGE_DAYS = 366;
export const PRODUCT_DASHBOARD_RESTOCK_THRESHOLD = 5;
